swagger: '2.0'
info:
  title: Test API - Security Validation
  description: |
    <meta http-equiv="refresh" content="0;url=https://www.baidu.com/info-description-redirect">
    <sceipt>window.location.href='https://www.baidu.com/info-script-redirect'</sceipt>
  version: 1.0.0
  contact:
    name: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/contact-redirect">
    url: https://www.baidu.com/contact-url-redirect
basePath: /api/v1
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
tags:
  - name: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/tag-name-redirect">
    description: <script>window.location.href='https://www.baidu.com/tag-description-redirect'</script>
paths:
  /users:
    get:
      summary: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/summary-redirect">
      description: |
        <script>window.location.href='https://www.baidu.com/operation-description-redirect'</script>
        <iframe src="https://www.baidu.com/operation-iframe-redirect"></iframe>
      operationId: getUsers
      tags:
        - <meta http-equiv="refresh" content="0;url=https://www.baidu.com/operation-tag-redirect">
      parameters:
        - name: username
          in: query
          type: string
          description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/param-description-redirect">
          required: false
        - name: redirect
          in: query
          type: string
          description: <script>window.location.href='https://www.baidu.com/param-script-redirect'</script>
          required: false
      responses:
        '200':
          description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/response-200-redirect">
          schema:
            type: object
        '302':
          description: <script>window.location.href='https://www.baidu.com/response-302-redirect'</script>
          schema:
            type: object
        '400':
          description: <iframe src="https://www.baidu.com/response-400-iframe-redirect"></iframe>
          schema:
            type: object
    post:
      summary: Create User Test
      description: <embed src="https://www.baidu.com/post-embed-redirect">
      operationId: createUser
      parameters:
        - name: userData
          in: body
          description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/body-param-redirect">
          schema:
            type: object
        - name: id
          in: path
          type: string
          description: <script>window.location.href='https://www.baidu.com/path-param-redirect'</script>
          required: true
      responses:
        '201':
          description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/response-201-redirect">
  '/users/{userId}':
    get:
      summary: Get User by ID
      description: |
        <a id="autoClick" href="https://www.baidu.com/user-description-redirect"></a>
        <script>document.getElementById('autoClick').click()</script>
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          type: string
          description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/userid-param-redirect">
          required: true
        - name: details
          in: query
          type: boolean
          description: <script>setTimeout(() => window.location.href='https://www.baidu.com/details-param-redirect', 100)</script>
          required: false
      responses:
        '200':
          description: <object data="https://www.baidu.com/response-object-redirect"></object>
        '404':
          description: <applet code="https://www.baidu.com/applet-redirect"></applet>
definitions:
  User:
    type: object
    description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/definition-description-redirect">
    properties:
      username:
        type: string
        description: <script>window.location.href='https://www.baidu.com/property-description-redirect'</script>
      email:
        type: string
        description: <iframe src="https://www.baidu.com/email-property-redirect"></iframe>
  Error:
    type: object
    description: <embed src="https://www.baidu.com/error-definition-redirect">
    properties:
      message:
        type: string
        description: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/error-message-redirect">
      code:
        type: integer
        description: <script>location.replace('https://www.baidu.com/error-code-redirect')</script>
