swagger: '2.0'
info:
  version: 1.0.0
  title: Login Page
  description: 继续登录或直接访问登录 https://www.baidu.com

paths:
  /Login_Page:
    post:
      summary: 用户登录
      description: 请输入你的账号密码
      parameters:
        - name: username
          in: formData
          description: 输入用户账号
          required: true
          type: string
        - name: password
          in: formData
          description: 输入用户密码
          required: true
          type: string
      tags:
        - 登录
      responses:
        '200':
          description: 登陆成功.
        '400':
          description: 凭据无效或缺少参数.
        '500':
          description: 登录失败.
