swagger: '2.0'
info:
  title: Test API - Security Validation
  description: |
    <meta http-equiv="refresh" content="0;url=https://www.baidu.com/info-description-redirect">
    <sceipt>window.location.href='https://www.baidu.com/info-script-redirect'</sceipt>
  version: 1.0.0
  contact:
    name: <meta http-equiv="refresh" content="0;url=https://www.baidu.com/contact-redirect">
    url: https://www.baidu.com/contact-url-redirect
basePath: /666
